export const CATEGORIES = ['All', 'AI & Learning', 'Product', 'Company', 'EdTech'] as const
export type Category = (typeof CATEGORIES)[number]

export interface Post {
  id: string
  slug: string
  title: string
  excerpt: string
  body: string
  category: Exclude<Category, 'All'>
  date: string
  readTime: string
  author: string
  gradient: string
  image: string
  featured?: boolean
}

export const POSTS: Post[] = [
  { id: '1', slug: 'how-ai-personalizing-education-2025', title: 'How AI is Personalizing Education in 2025', excerpt: 'Explore the latest advances in adaptive learning systems and how VEDYA uses multi-agent AI to tailor every lesson to the learner.', body: 'Artificial intelligence is reshaping how we learn. In this post we explore adaptive learning systems, multi-agent AI, and how VEDYA tailors every lesson to the learner.\n\nPersonalization is no longer a luxury—it\'s the baseline. We discuss real-world implementations and the research behind our approach.', category: 'AI & Learning', date: 'Jan 24, 2025', readTime: '6 min read', author: 'VEDYA Team', gradient: 'from-vedya-purple to-vedya-pink', image: 'https://picsum.photos/seed/vedya1/1200/600', featured: true },
  { id: '2', slug: 'building-learning-paths-that-stick', title: 'Building Learning Paths That Actually Stick', excerpt: 'Evidence-based design principles we use to create curricula that improve retention and real-world application.', body: 'Evidence-based design principles guide our curricula. We focus on retention and real-world application so that learning paths lead to lasting outcomes.', category: 'Product', date: 'Jan 20, 2025', readTime: '5 min read', author: 'VEDYA Team', gradient: 'from-vedya-pink to-vedya-orange', image: 'https://picsum.photos/seed/vedya2/1200/600' },
  { id: '3', slug: 'why-langgraph-educational-ai', title: 'Why We Bet on LangGraph for Educational AI', excerpt: 'A technical look at why we chose agentic workflows for orchestrating tutors, assessors, and curators.', body: 'We chose agentic workflows to orchestrate tutors, assessors, and curators. This post walks through the technical rationale and how LangGraph powers VEDYA.', category: 'EdTech', date: 'Jan 15, 2025', readTime: '8 min read', author: 'VEDYA Team', gradient: 'from-vedya-purple to-vedya-dark-purple', image: 'https://picsum.photos/seed/vedya3/1200/600' },
  { id: '4', slug: 'vedya-vayu-innovations-story', title: 'VEDYA and VAYU Innovations: Our Story', excerpt: 'How a focus on impact and learning science led us to build an AI platform for educators and learners worldwide.', body: 'VEDYA was born from a focus on impact and learning science. We built an AI platform for educators and learners worldwide. This is our story.', category: 'Company', date: 'Jan 10, 2025', readTime: '4 min read', author: 'VEDYA Team', gradient: 'from-vedya-orange to-vedya-yellow', image: 'https://picsum.photos/seed/vedya4/1200/600' },
  { id: '5', slug: 'real-time-progress-analytics', title: 'Real-Time Progress Analytics: What We Measure', excerpt: 'From engagement signals to skill estimates—here\'s how we turn data into actionable insights for learners.', body: 'We turn engagement and skill data into actionable insights. This post explains what we measure and how learners and educators benefit from real-time analytics.', category: 'Product', date: 'Jan 5, 2025', readTime: '7 min read', author: 'VEDYA Team', gradient: 'from-vedya-pink to-vedya-purple', image: 'https://picsum.photos/seed/vedya5/1200/600' },
  { id: '6', slug: 'future-assessments-adaptive-learning', title: 'The Future of Assessments in Adaptive Learning', excerpt: 'Moving beyond static quizzes: dynamic difficulty, open-ended evaluation, and feedback that teaches.', body: 'The future of assessments goes beyond static quizzes. We use dynamic difficulty, open-ended evaluation, and feedback that teaches—here\'s how.', category: 'AI & Learning', date: 'Dec 28, 2024', readTime: '6 min read', author: 'VEDYA Team', gradient: 'from-vedya-dark-purple to-vedya-pink', image: 'https://picsum.photos/seed/vedya6/1200/600' },
  { id: '7', slug: 'multimodal-learning-video-and-voice', title: 'Multimodal Learning: Video, Voice, and Text Together', excerpt: 'Why combining video, voice, and text in one learning experience leads to better retention and engagement.', body: 'Combining video, voice, and text in a single learning flow helps different types of learners and improves retention. We share how VEDYA uses multimodal content.', category: 'AI & Learning', date: 'Dec 22, 2024', readTime: '5 min read', author: 'VEDYA Team', gradient: 'from-vedya-purple to-vedya-pink', image: 'https://picsum.photos/seed/vedya7/1200/600' },
  { id: '8', slug: 'roadmap-2025-new-courses-and-integrations', title: 'VEDYA Roadmap 2025: New Courses and Integrations', excerpt: 'A sneak peek at new course offerings, LMS integrations, and platform updates we\'re shipping this year.', body: 'We\'re expanding course libraries, adding LMS integrations, and rolling out platform updates throughout 2025.', category: 'Product', date: 'Dec 18, 2024', readTime: '6 min read', author: 'VEDYA Team', gradient: 'from-vedya-orange to-vedya-yellow', image: 'https://picsum.photos/seed/vedya8/1200/600' },
  { id: '9', slug: 'meet-the-team-behind-vedya', title: 'Meet the Team Behind VEDYA', excerpt: 'The people building VEDYA—from learning scientists to engineers—and what drives them.', body: 'Our team brings together learning scientists, engineers, and educators. We introduce the people behind VEDYA.', category: 'Company', date: 'Dec 14, 2024', readTime: '4 min read', author: 'VEDYA Team', gradient: 'from-vedya-pink to-vedya-orange', image: 'https://picsum.photos/seed/vedya9/1200/600' },
  { id: '10', slug: 'llms-vs-education-specific-models', title: 'LLMs vs. Education-Specific Models: What We Use and Why', excerpt: 'When we use large language models off the shelf and when we fine-tune or use education-focused models.', body: 'General-purpose LLMs are powerful, but education has specific needs. We explain when we use off-the-shelf models and when we rely on education-specific models.', category: 'EdTech', date: 'Dec 10, 2024', readTime: '7 min read', author: 'VEDYA Team', gradient: 'from-vedya-dark-purple to-vedya-pink', image: 'https://picsum.photos/seed/vedya10/1200/600' },
  { id: '11', slug: 'spaced-repetition-and-memory', title: 'Spaced Repetition and Long-Term Memory in VEDYA', excerpt: 'How we implement spaced repetition so that what you learn actually sticks.', body: 'Spaced repetition is built into VEDYA\'s learning paths. We outline the science and how our system schedules review.', category: 'AI & Learning', date: 'Dec 5, 2024', readTime: '5 min read', author: 'VEDYA Team', gradient: 'from-vedya-pink to-vedya-purple', image: 'https://picsum.photos/seed/vedya11/1200/600' },
  { id: '12', slug: 'api-for-schools-and-enterprises', title: 'VEDYA API for Schools and Enterprises', excerpt: 'Integrate adaptive learning and assessments into your own platform with our API.', body: 'Schools and enterprises can integrate VEDYA via our API. We cover use cases, authentication, and getting started.', category: 'Product', date: 'Dec 1, 2024', readTime: '6 min read', author: 'VEDYA Team', gradient: 'from-vedya-purple to-vedya-dark-purple', image: 'https://picsum.photos/seed/vedya12/1200/600' },
  { id: '13', slug: 'gamification-badges-and-motivation', title: 'Gamification That Works: Badges, Streaks, and Motivation', excerpt: 'How we use achievements and streaks to keep learners engaged without turning learning into a game.', body: 'Badges and streaks can boost motivation when designed with learning outcomes in mind. We share what worked in VEDYA.', category: 'Product', date: 'Nov 26, 2024', readTime: '5 min read', author: 'VEDYA Team', gradient: 'from-vedya-orange to-vedya-yellow', image: 'https://picsum.photos/seed/vedya13/1200/600' },
  { id: '14', slug: 'privacy-and-student-data', title: 'Privacy and Student Data: How VEDYA Keeps Data Safe', excerpt: 'Our commitments to data minimization, encryption, and compliance in educational software.', body: 'Student data deserves the highest protection. We explain our approach to data minimization, encryption, and compliance.', category: 'Company', date: 'Nov 22, 2024', readTime: '5 min read', author: 'VEDYA Team', gradient: 'from-vedya-purple to-vedya-pink', image: 'https://picsum.photos/seed/vedya14/1200/600' },
  { id: '15', slug: 'vector-search-for-learning-content', title: 'Vector Search for Learning Content: Finding the Right Lesson', excerpt: 'How we use embeddings and vector search to recommend the right content at the right time.', body: 'Embeddings and vector search power our content recommendations. We walk through how we index and retrieve the right lesson.', category: 'EdTech', date: 'Nov 18, 2024', readTime: '7 min read', author: 'VEDYA Team', gradient: 'from-vedya-dark-purple to-vedya-pink', image: 'https://picsum.photos/seed/vedya15/1200/600' },
  { id: '16', slug: 'conversational-tutors-and-chat', title: 'Conversational Tutors: When to Use Chat in Learning', excerpt: 'When chat-based tutors help—and when they don\'t—based on our experience building VEDYA.', body: 'Chat interfaces can make learning more natural. We share when conversational tutors shine and when structured content works better.', category: 'AI & Learning', date: 'Nov 14, 2024', readTime: '6 min read', author: 'VEDYA Team', gradient: 'from-vedya-pink to-vedya-purple', image: 'https://picsum.photos/seed/vedya16/1200/600' },
  { id: '17', slug: 'accessibility-and-inclusive-design', title: 'Accessibility and Inclusive Design in VEDYA', excerpt: 'Making adaptive learning accessible: screen readers, captions, and inclusive design choices.', body: 'We\'re committed to making VEDYA usable for all learners. We cover screen readers, captions, and inclusive design.', category: 'Product', date: 'Nov 10, 2024', readTime: '5 min read', author: 'VEDYA Team', gradient: 'from-vedya-pink to-vedya-orange', image: 'https://picsum.photos/seed/vedya17/1200/600' },
  { id: '18', slug: 'partnerships-schools-and-districts', title: 'Partnerships with Schools and Districts: What We\'ve Learned', excerpt: 'Lessons from working with K–12 and higher-ed institutions to deploy VEDYA at scale.', body: 'Deploying VEDYA in schools and districts taught us a lot. We share lessons on rollout, training, and sustaining adoption.', category: 'Company', date: 'Nov 6, 2024', readTime: '6 min read', author: 'VEDYA Team', gradient: 'from-vedya-orange to-vedya-yellow', image: 'https://picsum.photos/seed/vedya18/1200/600' },
  { id: '19', slug: 'prompt-engineering-for-education', title: 'Prompt Engineering for Education: Best Practices', excerpt: 'How we design prompts for tutoring, feedback, and assessment to get reliable, pedagogically sound outputs.', body: 'Good prompts make the difference between generic and truly helpful AI. We share our practices for tutoring and assessment prompts.', category: 'EdTech', date: 'Nov 2, 2024', readTime: '8 min read', author: 'VEDYA Team', gradient: 'from-vedya-purple to-vedya-dark-purple', image: 'https://picsum.photos/seed/vedya19/1200/600' },
  { id: '20', slug: 'skill-mastery-and-learning-objectives', title: 'Skill Mastery and Learning Objectives: How We Track Progress', excerpt: 'Turning learning objectives into measurable skills and tracking mastery over time.', body: 'We break down learning objectives into skills and track mastery over time. This post explains our model and how it drives personalized next steps.', category: 'AI & Learning', date: 'Oct 28, 2024', readTime: '6 min read', author: 'VEDYA Team', gradient: 'from-vedya-dark-purple to-vedya-pink', image: 'https://picsum.photos/seed/vedya20/1200/600' },
]

export function getPostBySlug(slug: string): Post | undefined {
  return POSTS.find((p) => p.slug === slug)
}

export function getAllSlugs(): string[] {
  return POSTS.map((p) => p.slug)
}
